showonpause=no
show_title=no
time_font_size=20
show_file_size=no
description_font_size=20
info_button=yes
screenshot_button=yes
download_path=~/Videos/mpv/
hover_effect=no
seekbarhandlesize=1
persistentprogressheight=20
persistentbuffer=yes
